export const availableVoices = [
  { name: 'Echo', description: 'Clear, neutral tone, standard pitch.' },
  { name: 'Calamity', description: 'Deep, resonant, with a serious tone.' },
  { name: 'Zephyr', description: 'Light, airy, and gentle.' },
  { name: 'Puck', description: 'Playful, higher pitch, energetic.' },
  { name: 'Kore', description: 'Authoritative, calm, and measured.' },
  { name: 'Fenrir', description: 'Gruff, low-pitched, and imposing.' },
  { name: 'Nyx', description: 'Soft, mysterious, and slightly hushed.' },
  { name: 'Charon', description: 'Gravelly, slow, and solemn.' },
  { name: 'Calypso', description: 'Melodic, smooth, and engaging.' },
  { name: 'Jinx', description: 'Youthful, raspy, and informal.' },
  { name: 'Oberon', description: 'Regal, commanding, and rich.' },
  { name: 'Rhea', description: 'Warm, maternal, and comforting.' },
  { name: 'Alphekka', description: 'Bright, crisp, and articulate.' },
  { name: 'Elnath', description: 'Strong, steady, and confident.' },
  { name: 'Deneb', description: 'Bright, professional, and clear.' },
  { name: 'Algenib', description: 'Steady, medium pitch, trustworthy.' },
  { name: 'Enif', description: 'Lower pitch, professional, and warm.' },
  { name: 'Capella', description: 'Upbeat, friendly, and bright.' },
  { name: 'Sirius', description: 'Deep, authoritative, and very clear.' },
  { name: 'Canopus', description: 'Smooth, relaxed, and reassuring.' },
  { name: 'Rigel', description: 'Bright, energetic, and youthful.' },
  { name: 'Vega', description: 'Crisp, professional, and articulate.' },
  { name: 'Arcturus', description: 'Warm, deep, and avuncular.' },
  { name: 'Achernar', description: 'Calm, steady, and neutral.' },
  { name: 'Hadar', description: 'Low pitch, serious, and resonant.' },
  { name: 'Spica', description: 'Bright, higher pitch, and friendly.' },
  { name: 'Antares', description: 'Deep, gravelly, and commanding.' },
];
