export const availableVoices = [
  { name: 'Zephyr', description: 'Brillante, Tono más alto' },
  { name: 'Puck', description: 'Animado, Tono medio' },
  { name: 'Charon', description: 'Informativo, Tono más bajo' },
  { name: 'Kore', description: 'Firme, Tono medio' },
  { name: 'Fenrir', description: 'Excitable, Tono medio-bajo' },
  { name: 'Leda', description: 'Juvenil, Tono más alto' },
  { name: 'Orus', description: 'Firme, Tono medio-bajo' },
  { name: 'Aoede', description: 'Fresco, Tono medio' },
  { name: 'Callirrhoe', description: 'Relajado, Tono medio' },
  { name: 'Autonoe', description: 'Brillante, Tono medio' },
  { name: 'Enceladus', description: 'Con voz entrecortada, Tono más bajo' },
  { name: 'Iapetus', description: 'Claro, Tono medio-bajo' },
  { name: 'Umbriel', description: 'Relajado, Tono medio-bajo' },
  { name: 'Algieba', description: 'Suave, Tono más bajo' },
  { name: 'Despina', description: 'Suave, Tono medio' },
  { name: 'Erinome', description: 'Claro, Tono medio' },
  { name: 'Algenib', description: 'Ronco, Tono más bajo' },
  { name: 'Rasalgethi', description: 'Informativo, Tono medio' },
  { name: 'Laomedeia', description: 'Animado, Tono más alto' },
  { name: 'Achernar', description: 'Suave, Tono más alto' },
  { name: 'Alnilam', description: 'Firme, Tono medio-bajo' },
  { name: 'Schedar', description: 'Uniforme, Tono medio-bajo' },
  { name: 'Gacrux', description: 'Maduro, Tono medio' },
  { name: 'Pulcherrima', description: 'Adelantado, Tono medio' },
  { name: 'Achird', description: 'Amigable, Tono medio-bajo' },
  { name: 'Zubenelgenubi', description: 'Casual, Tono medio-bajo' },
  { name: 'Vindemiatrix', description: 'Suave, Tono medio' },
  { name: 'Sadachbia', description: 'Animado, Tono más bajo' },
  { name: 'Sadaltager', description: 'Conocedor, Tono medio' },
  { name: 'Sulafat', description: 'Cálido, Tono medio' },
];
